version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo_container
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    container_name: backend_container
    image: matecia-backend
    build:
      context: ./portalapi
    volumes:
      - ./portalapi:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    command: npx nodemon src/index.js
    restart: always
    depends_on:
      - mongo

  frontend:
    build: ./portal
    container_name: frontend_container
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./portal:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0   # Fix React polling in Docker
    depends_on:
      - backend

volumes:
  mongo_data:
